#!/bin/bash
# https://github.com/fuku77/

colors=$4

echo "#!/bin/bash
# This file is auto generated.

export \\
FK_THEME=\"$1\" \\
FK_FILE_BROWSER=\"$7\" \\
FK_TERMINAL=\"$8\" \\
FK_WALLPAPER=\"$2\" \\
FK_PICOM_ADD_SETTINGS=\"$3\" \\
\\
FK_SCRIPT_DIR=\"$5\" \\
FK_DIR=\"$6\" \\
\\
FK_COLOR_BG=\"${colors:0:7}\" \\
FK_COLOR_FG=\"${colors:7:7}\" \\
FK_COLOR_00=\"${colors:14:7}\" \\
FK_COLOR_01=\"${colors:21:7}\" \\
FK_COLOR_02=\"${colors:28:7}\" \\
FK_COLOR_03=\"${colors:35:7}\" \\
FK_COLOR_04=\"${colors:42:7}\" \\
FK_COLOR_05=\"${colors:49:7}\" \\
FK_COLOR_06=\"${colors:56:7}\" \\
FK_COLOR_07=\"${colors:63:7}\" \\
FK_COLOR_08=\"${colors:70:7}\" \\
FK_COLOR_09=\"${colors:77:7}\" \\
FK_COLOR_10=\"${colors:84:7}\" \\
FK_COLOR_11=\"${colors:91:7}\" \\
FK_COLOR_12=\"${colors:98:7}\" \\
FK_COLOR_13=\"${colors:105:7}\" \\
FK_COLOR_14=\"${colors:112:7}\" \\
FK_COLOR_15=\"${colors:119:7}\" \\
FK_COLOR_DOM=\"${colors:126:7}\"
" > ~/.fk/env
